//REGISTER ADMIN
POST http://localhost:5000/register 
Content-Type: application/json 

{
    "nama": "admin",
    "email": "admin@gmail.com",
    "password": "admin1",
    "confPassword":"admin1",
    "departemen":"SPM",
    "role": "admin"
}
//LOGIN ADMIN
###
POST http://localhost:5000/login
Content-Type: application/json 

{
    "email": "admin@gmail.com",
    "password": "admin1"
}

###
//GET ALL USER 
GET http://localhost:5000/users/81c98164-aafb-4976-8d6d-e55d3b2631d5

###
GET http://localhost:5000/departemen
###
//GET USER BY ID
GET http://localhost:5000/users/a8f271e5-b3eb-4f65-abf5-00a67b73344e
Content-Type: application/json 

//Logout
###
DELETE http://localhost:5000/users/a8f271e5-b3eb-4f65-abf5-00a67b73344e
Content-Type: application/json 

###
//Logout
DELETE http://localhost:5000/logout
Content-Type: application/json 


###
//SIPA AKU ?
GET http://localhost:5000/Me

###
//Buat surat izin
POST http://localhost:5000/suratizin
Content-Type: application/json 

{
    "nama_perizinan": "JAGO",
    "pic": "AYdfs",
    "nomor_perizinan": "099999",
    "from_email": "11201004@student.itk.ac.id",
    "departemen": "gaulsedunia",
    "tanggal_dibuat":"2023-08-10",
    "tanggal_berakhir":"2023-08-23",
    "image":"image",
    "uploadFile": "uploadFile"
}

###
//GET SEMUA SURAT IZIN
GET http://localhost:5000/suratizin
###
//GET SURAT IZIN BY ID
GET http://localhost:5000/suratizin/91fc431d-bda3-413b-9279-9694c3111ec6
Content-Type: application/json 

###
//UPDATE SURAT IZIN
PATCH http://localhost:5000/suratizin/6aba3c2e-4f69-441e-8f3f-123b4ff90642
Content-Type: application/json 

{
    "nama_perizinan": "namad",
    "pic": "maulfcom",
    "departemen": "HIDUPP",
    "tanggalExp":"2023-08-10",
    "reminder":"2023-08-10",
    "uploadFile": "uploadFile"
}
###
//HAPUS SURAT IZIN
DELETE http://localhost:5000/suratizin/6aba3c2e-4f69-441e-8f3f-123b4ff90642
Content-Type: application/json 
